# Generated by Django 5.1.7 on 2025-03-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lecturer_rename_age_student_student_age_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecturer',
            table='lecturers',
        ),
    ]
