# Generated by Django 5.1.7 on 2025-04-14 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_alter_dish_options_dish_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
