# Generated by Django 5.1.7 on 2025-04-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
