# Generated by Django 5.1.7 on 2025-04-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dish_dish_image_dish_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='unknown_category', max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(default='unknown_dish', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='core.category'),
        ),
    ]
