# Generated by Django 5.1.7 on 2025-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_slug_dish_slug_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
