# Generated by Django 5.1.7 on 2025-04-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_slug_alter_dish_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
