# Generated by Django 5.1.7 on 2025-04-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
