# Generated by Django 5.1.7 on 2025-04-22 16:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_category_slug_category_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dish',
            managers=[
                ('dishes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_description',
            field=models.TextField(blank=True),
        ),
    ]
